/// This code is generated by the `openrpc generate` subcommand.
// TODO(aatifsyed): this could be put in a separate crate to improve compile times
mod generated;

use std::{
    any::type_name,
    collections::BTreeSet,
    convert::Infallible,
    fmt,
    io::{self, Read as _, Write as _},
    mem,
    panic::{self, AssertUnwindSafe},
    process,
    time::Duration,
};

use ez_jsonrpc::{
    params::SerializePositional,
    types::{self as jsonrpc, RequestParameters},
};
use owo_colors::OwoColorize as _;
use serde::de::DeserializeOwned;

/// Represents that a single test has failed - the runner may stop running.
///
/// This SHOULD be propogated with the `?` operator.
// This is a shim of anyhow::Error to enforce semantics.
// We hide Send + Sync + 'static bounds for messages to hide complexity.
pub struct TestFailure(anyhow::Error);

impl TestFailure {
    pub fn msg(msg: impl fmt::Display) -> Self {
        Self(anyhow::Error::msg(msg.to_string()))
    }
    pub fn context(self, msg: impl fmt::Display) -> Self {
        Self(self.0.context(msg.to_string()))
    }
    /// See [`Ctx::call`].
    pub fn as_rpc_error(&self) -> Option<&jsonrpc::Error> {
        self.0.downcast_ref()
    }
    #[doc(hidden)]
    #[deprecated = "not public API"]
    pub fn __new(e: anyhow::Error) -> Self {
        Self(e)
    }
}

impl<T> From<T> for TestFailure
where
    T: std::error::Error + Send + Sync + 'static,
{
    fn from(value: T) -> Self {
        Self(value.into())
    }
}

mod sealed {
    pub trait Sealed {}
    impl<T, E> Sealed for Result<T, E> {}
    impl<T> Sealed for Option<T> {}
}

/// Utility trait for failing a test on a [`Result::Err`] or [`Option::None`].
pub trait Context<T, E>: sealed::Sealed {
    fn context<C: fmt::Display>(self, context: C) -> Result<T, TestFailure>;
}

impl<T, E> Context<T, E> for Result<T, E>
where
    E: std::error::Error + Send + Sync + 'static,
{
    fn context<C: fmt::Display>(self, context: C) -> Result<T, TestFailure> {
        anyhow::Context::context(self, context.to_string()).map_err(TestFailure)
    }
}

impl<T> Context<T, Infallible> for Option<T> {
    fn context<C: fmt::Display>(self, context: C) -> Result<T, TestFailure> {
        anyhow::Context::context(self, context.to_string()).map_err(TestFailure)
    }
}

/// Create a test case.
///
/// `name` SHOULD:
/// - be unique.
/// - fit on a single line, with no punctuation.
pub fn test<'a>(
    name: impl Into<String>,
    f: impl FnOnce(&mut Ctx) -> Result<(), TestFailure> + 'a,
) -> Test<'a> {
    Test {
        name: name.into(),
        runner: Box::new(f),
    }
}

/// Dynamic test case, created with the [`test`] function.
pub struct Test<'a> {
    name: String,
    #[allow(clippy::type_complexity)]
    runner: Box<dyn FnOnce(&mut Ctx) -> Result<(), TestFailure> + 'a>,
}

/// Closed set of tags for the test suite.
#[derive(strum::Display, strum::EnumString, PartialEq, Eq, PartialOrd, Ord, Debug, Clone)]
#[strum(serialize_all = "snake_case")]
pub enum Tag {
    /// Simple test that just tries to cover schemas.
    Basic,
}

/// Context for a [`Test`].
///
/// You may use this to:
/// - Send and receive JSON-RPC requests.
/// - Request resources like snapshots from the runner.
/// - Categorize your test.
#[derive(Debug)]
pub struct Ctx {
    client: reqwest::blocking::Client,
    url: String,
    id: u64,
    current_test_tags: BTreeSet<Tag>,
    log: Vec<Log>,

    harness_tags: BTreeSet<Tag>,

    done_first_call: bool,

    timeout_mode: Timeout,
    harness_timeout_default: Duration,
    harness_timeout_long: Duration,

    auth_mode: Auth,
    harness_auth_bad: String,
    harness_auth_good: String,
}

#[derive(Debug, Clone, Copy)]
enum Timeout {
    Default,
    Long,
}

#[derive(Debug, Clone, Copy)]
enum Auth {
    None,
    Bad,
    Good,
}

impl Ctx {
    fn filter(&self) -> Result<(), Ignored> {
        match self.harness_tags.is_empty() {
            false if !self.harness_tags.is_subset(&self.current_test_tags) => Err(Ignored),
            _ => Ok(()),
        }
    }

    /// Apply tags to this [`Test`].
    ///
    /// This MUST be done before any JSON-RPC method calls,
    /// and SHOULD NOT be conditional.
    #[allow(private_bounds)]
    pub fn tag(&mut self, tags: impl TagCtx) {
        assert!(
            !self.done_first_call,
            "Ctx::tag must be called before any method calls"
        );
        tags.tag_ctx(&mut self.current_test_tags);
    }

    /// [`Self::call`]s after this will use a longer timeout.
    pub fn long_timeout(&mut self) {
        self.timeout_mode = Timeout::Long
    }

    /// [`Self::call`]s after this will use the default timeout.
    pub fn normal_timeout(&mut self) {
        self.timeout_mode = Timeout::Default
    }

    /// [`Self::call`]s after this will be unauthorised.
    pub fn no_auth(&mut self) {
        self.auth_mode = Auth::None
    }
    /// [`Self::call`]s after this will have authorisation.
    /// (This is the default).
    pub fn good_auth(&mut self) {
        self.auth_mode = Auth::Good
    }
    /// [`Self::call`]s after this will have malformed authorisation.
    pub fn bad_auth(&mut self) {
        self.auth_mode = Auth::Bad
    }
    pub fn log(&mut self, msg: impl fmt::Display) {
        self.log.push(Log::User(msg.to_string()))
    }

    /// Call a JSON-RPC method.
    ///
    /// JSON-RPC [specifies an error object](https://www.jsonrpc.org/specification#error_object)
    /// that all methods may return.
    ///
    /// Such errors are assumed to _also_ be [`TestFailure`]s -
    /// you may manually check to see if a method returned an error by calling
    /// [`TestFailure::as_rpc_error`].
    pub fn call<T: DeserializeOwned>(
        &mut self,
        method: impl Into<String>,
        args: impl SerializePositional,
    ) -> Result<T, TestFailure> {
        self.done_first_call = true;
        self.filter()?;

        self.id += 1;
        let request_id = jsonrpc::Id::Number(self.id.into());
        let request = jsonrpc::Request {
            method: method.into(),
            params: Some(RequestParameters::ByPosition(
                args.ser_positional(ez_jsonrpc::params::ser::ByPosition::new())
                    .context("couldn't serialize params")?,
            )),
            id: Some(request_id.clone()),
        };
        self.log.push(Log::Request(request.clone()));
        let builder = self
            .client
            .post(&self.url)
            .json(&request)
            .timeout(match self.timeout_mode {
                Timeout::Default => self.harness_timeout_default,
                Timeout::Long => self.harness_timeout_long,
            });

        let mut resp = match self.auth_mode {
            Auth::None => builder,
            Auth::Bad => builder.bearer_auth(&self.harness_auth_bad),
            Auth::Good => builder,
        }
        .send()
        .context("couldn't send HTTP request")?;
        let mut body = vec![];
        resp.read_to_end(&mut body)
            .context("couldn't collect HTTP response body from server")?;
        match (
            resp.error_for_status().context("HTTP error from server"),
            serde_json::from_slice::<jsonrpc::Response>(&body)
                .context("invalid JSON-RPC response from server"),
        ) {
            (Err(e), _) | (_, Err(e)) => {
                self.log.push(Log::Body(body));
                Err(e)
            }
            (_, Ok(response)) => {
                self.log.push(Log::Response(response.clone()));
                if request_id != response.id {
                    fail!("server violated the JSON-RPC protocol (member `id` does not match)")
                }
                let o = response.result.context("JSON-RPC call returned an error")?;
                dbg!(&o);
                let o = T::deserialize(o).context(format!(
                    "couldn't deserialize JSON-RPC response into a {}",
                    type_name::<T>()
                ))?;
                Ok(o)
            }
        }
    }
}

#[derive(clap::Parser)]
pub struct Args {
    /// Only run the test with the given name.
    #[arg(long)]
    pub name: Option<String>,
    /// If [`Some`], only run [`Test`]s which contain all of the given [`Tag`]s.
    #[arg(long)]
    pub tags: Vec<Tag>,
    #[arg(long)]
    pub url: String,
    #[arg(long, default_value = "60")]
    pub default_timeout: f64,
    #[arg(long, default_value = "120")]
    pub long_timeout: f64,
    #[arg(long)]
    pub auth: String,
    #[arg(long, default_value = "not-a-token")]
    pub bad_auth: String,
}

/// Run the given test cases.
///
/// This SHOULD only be called once, unconditionally.
pub fn run<'a>(tests: impl IntoIterator<Item = Test<'a>>, args: Args) -> anyhow::Result<()> {
    let mut tests = tests.into_iter().collect::<Vec<_>>();
    tests.sort_by_cached_key(|it| it.name.clone());

    let Args {
        name: filter_name,
        tags,
        url,
        default_timeout,
        long_timeout,
        auth,
        bad_auth,
    } = args;

    let mut skipped = 0;
    let mut succeeded = 0;
    let mut failed = 0;

    let mut ctx = Ctx {
        client: reqwest::blocking::Client::builder()
            .user_agent(concat!(
                env!("CARGO_PKG_NAME"),
                "/",
                env!("CARGO_PKG_VERSION")
            ))
            .build()
            .expect("couldn't initialize client"),
        url,
        log: vec![],

        id: 0,
        current_test_tags: BTreeSet::new(),
        harness_tags: tags.into_iter().collect(),
        done_first_call: false,

        timeout_mode: Timeout::Default,
        harness_timeout_default: Duration::from_secs_f64(default_timeout),
        harness_timeout_long: Duration::from_secs_f64(long_timeout),

        auth_mode: Auth::Good,
        harness_auth_bad: bad_auth,
        harness_auth_good: auth,
    };

    let stdout = &mut anstream::AutoStream::auto(io::stdout());
    let mut failed_logs = vec![];

    // TODO(aatifsyed): siphon off a backtrace and log it
    panic::set_hook(Box::new(|_| {}));
    for (ix, Test { name, runner }) in tests.into_iter().enumerate() {
        write!(
            stdout,
            "{}\t{}{}",
            ix.dimmed(),
            name.white(),
            "... ".dimmed()
        )?;
        let res = match &filter_name {
            Some(filter_name) => match name == *filter_name {
                true => panic::catch_unwind(AssertUnwindSafe(|| runner(&mut ctx))),
                false => {
                    writeln!(stdout, "{}", "skipped (name)".yellow())?;
                    skipped += 1;
                    continue;
                }
            },
            None => panic::catch_unwind(AssertUnwindSafe(|| runner(&mut ctx))),
        };
        match res {
            Ok(Ok(())) => {
                writeln!(stdout, "{}", "passed".green())?;
                succeeded += 1;
            }
            Ok(Err(TestFailure(e))) => match e.downcast_ref::<Ignored>() {
                Some(_) => {
                    writeln!(stdout, "{}", "skipped (tag)".yellow())?;
                    skipped += 1
                }
                None => {
                    writeln!(stdout, "{}", "failed".red())?;
                    failed += 1;
                    ctx.log.push(Log::Errors(e));
                    write_logs(&mut *stdout, &ctx.log)?;
                    failed_logs.push((name, mem::take(&mut ctx.log)));
                }
            },
            Err(panic) => {
                let panic_msg = match (panic.downcast_ref::<String>(), panic.downcast_ref::<&str>())
                {
                    (Some(s), _) => s.as_str(),
                    (_, Some(s)) => s,
                    _ => "Box<dyn Any>",
                };
                writeln!(stdout, "{}", "failed".red())?;
                failed += 1;
                ctx.log
                    .push(Log::Errors(anyhow::Error::msg(panic_msg.to_string())));
                write_logs(&mut *stdout, &ctx.log)?;
                failed_logs.push((name, mem::take(&mut ctx.log)));
            }
        }

        ctx.current_test_tags.clear();
        ctx.log.clear();
        ctx.done_first_call = false;
        ctx.auth_mode = Auth::Good;
        ctx.timeout_mode = Timeout::Default;
    }
    let _unregister = panic::take_hook();

    for (ix, (name, logs)) in failed_logs.into_iter().enumerate() {
        writeln!(stdout, "failure {} ({})", ix, name)?;
        write_logs(&mut *stdout, &logs)?;
    }

    writeln!(
        stdout,
        "{} skipped, {} succeeded, {} failed",
        skipped, succeeded, failed
    )?;

    match failed {
        0 => process::exit(0),
        _ => process::exit(1),
    }
}

#[derive(thiserror::Error, Debug)]
#[error("ignored")]
struct Ignored;

/// Utility trait to allow [`Ctx::tag`] to accept either a single [`Tag`] or a
/// collection of many.
trait TagCtx {
    fn tag_ctx(self, tags: &mut BTreeSet<Tag>);
}

impl TagCtx for Tag {
    fn tag_ctx(self, tags: &mut BTreeSet<Tag>) {
        tags.insert(self);
    }
}

impl<T> TagCtx for T
where
    T: IntoIterator<Item = Tag>,
{
    fn tag_ctx(self, tags: &mut BTreeSet<Tag>) {
        tags.extend(self)
    }
}

macro_rules! fail {
    ($msg:literal $(,)?) => {
        #[allow(deprecated)]
        return ::core::result::Result::Err($crate::test::TestFailure::__new(::anyhow::anyhow!($msg)))
    };
    ($err:expr $(,)?) => {
        #[allow(deprecated)]
        return ::core::result::Result::Err($crate::test::TestFailure::__new(::anyhow::anyhow!($err)))
    };
    ($fmt:expr, $($arg:tt)*) => {
        #[allow(deprecated)]
        return ::core::result::Result::Err($crate::test::TestFailure::__new(::anyhow::anyhow!($fmt, $($arg)*)))
    };
}
pub(crate) use fail;

#[derive(Debug)]
enum Log {
    User(String),
    Request(jsonrpc::Request),
    Response(jsonrpc::Response),
    Body(Vec<u8>),
    Errors(anyhow::Error),
}

fn write_logs<'a>(
    mut writer: impl io::Write,
    logs: impl IntoIterator<Item = &'a Log>,
) -> anyhow::Result<()> {
    let w = &mut writer;
    for (ix, log) in logs.into_iter().enumerate() {
        match log {
            Log::User(msg) => writeln!(w, "\t{ix}\t{}\t{msg}", msg.blue())?,
            Log::Request(it) => {
                let it = serde_json::to_string_pretty(it)?;
                writeln!(w, "\t{ix}\t{}", "req".blue())?;
                for line in it.lines() {
                    writeln!(w, "\t{}", line)?
                }
            }
            Log::Response(it) => {
                let it = serde_json::to_string_pretty(it)?;
                writeln!(w, "\t{ix}\t{}", "resp".blue())?;
                for line in it.lines() {
                    writeln!(w, "\t{}", line)?
                }
            }
            Log::Body(it) => {
                writeln!(w, "\t{ix}\t{}", "body".blue())?;
                for line in String::from_utf8_lossy(it).lines() {
                    writeln!(w, "\t{}", line)?
                }
            }
            Log::Errors(e) => {
                writeln!(w, "\t{ix}\t{}", "err".blue())?;
                for err in e.chain() {
                    writeln!(w, "\t{}", err)?
                }
            }
        }
    }
    Ok(())
}
