[package]
name = "bindings"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
ez-jsonrpc = "0.2.0"
serde = { version = "1.0.207", features = ["derive"] }
serde_json = "1.0.124"
