name: Lint

on:
  pull_request:

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Print toolchain version
        run: rustup show active-toolchain

      - name: Run fmt
        run: make lint

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Print toolchain version
        run: rustup show active-toolchain

      - name: Run clippy
        run: make clippy